modid = "miehex"
book = "hexcasting:thehexbook"

resource_dirs = [  # top takes priority
    "resources",
    "{$_common.src}/main/resources",
    { path="{$_common.src}/generated/resources", required=false },
    "{$_fabric.src}/main/resources",
    { path="{$_fabric.src}/generated/resources", required=false },
    "{$_forge.src}/main/resources",
    { path="{$_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_miehex/_export/generated"

[template]
# TODO: change this to point to your actual mod icon
icon = "icon.png"
include = [
    "miehex",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Miehex"
author = "xm1221"
show_landing_text = false

[extra.hexcasting]
# regexes for parsing pattern registry files - if some or all of your patterns aren't being detected by hexdoc, this may need to be updated
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)' }

[[extra.hexcasting.pattern_stubs]]
path = "{$_common.src}/main/java/cn/xm1221/miehex/registry/ActionRegisry.java"
regex = "{^_pattern_regex}"

# source paths

[_common]
src = "../common/src"

[_fabric]
src = "../fabric/src"

[_forge]
src = "../forge/src"
